// This file is auto-generated by the build script
// Do not edit manually

declare const DASHBOARD_HTML: string;
declare const DRIVER_STATS_HTML: string;

// In production, these will be replaced by esbuild define
export const dashboardHtml = typeof DASHBOARD_HTML !== 'undefined' 
  ? DASHBOARD_HTML 
  : '';

export const driverStatsHtml = typeof DRIVER_STATS_HTML !== 'undefined'
  ? DRIVER_STATS_HTML
  : '';
