#!/usr/bin/env node
/**
 * Build script to inline HTML templates as TypeScript constants
 * This allows us to keep HTML as separate files during development
 * but bundle them into the worker at build time
 */

import * as fs from 'fs';
import * as path from 'path';

const TEMPLATES_DIR = './templates';
const OUTPUT_FILE = './src/generated/html-templates.ts';

// Template file structure
// name: filename
// variableName: generated TypeScript variable name
// content: escaped HTML content

function toValidVariableName(filename: string): string {
  return filename
    .replace(/\.html$/i, '')
    .replace(/[^a-zA-Z0-9]/g, '_')
    .toUpperCase() + '_HTML';
}

function escapeTemplateLiteral(content: string): string {
  return content
    .replace(/\\/g, '\\\\')  // Escape backslashes first
    .replace(/`/g, '\\`')     // Escape backticks
    .replace(/\$/g, '\\$');   // Escape dollar signs (for ${} interpolation)
}

function buildTemplates(): void {
  console.log('📦 Building HTML templates...\n');

  // Ensure templates directory exists
  if (!fs.existsSync(TEMPLATES_DIR)) {
    console.error(`❌ Templates directory not found: ${TEMPLATES_DIR}`);
    process.exit(1);
  }

  // Read all HTML files
  const files = fs.readdirSync(TEMPLATES_DIR)
    .filter(f => f.endsWith('.html'))
    .map(filename => {
      const filepath = path.join(TEMPLATES_DIR, filename);
      const content = fs.readFileSync(filepath, 'utf-8');
      
      return {
        name: filename,
        variableName: toValidVariableName(filename),
        content: escapeTemplateLiteral(content),
      };
    });

  if (files.length === 0) {
    console.warn('⚠️  No HTML templates found');
    return;
  }

  // Generate TypeScript file
  const generatedCode = `// Auto-generated by scripts/build-html.ts
// Do not edit this file manually
// Generated at: ${new Date().toISOString()}

${files.map(f => `export const ${f.variableName} = \`${f.content}\`;`).join('\n\n')}

// Template map for dynamic access
export const templates: Record<string, string> = {
${files.map(f => `  ${JSON.stringify(f.name)}: ${f.variableName},`).join('\n')}
};

// Helper function to get template
export function getTemplate(name: string): string {
  return templates[name] ?? '';
}
`;

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Write output file
  fs.writeFileSync(OUTPUT_FILE, generatedCode, 'utf-8');

  // Print summary
  console.log('✅ Templates built successfully!\n');
  console.log('Files processed:');
  files.forEach(f => {
    const sizeKB = (f.content.length / 1024).toFixed(2);
    console.log(`  • ${f.name} (${sizeKB} KB) → ${f.variableName}`);
  });
  console.log(`\nOutput: ${OUTPUT_FILE}`);
}

buildTemplates();
