#!/usr/bin/env node
/**
 * Build Tailwind CSS for the main worker and inline it as a TypeScript string export.
 */

import { execSync } from 'child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const rootDir = join(__dirname, '..');
const workerDir = join(rootDir, 'packages', 'main-worker');
const outDir = join(workerDir, 'src', 'generated');
const cssPath = join(outDir, 'styles.css');
const tsPath = join(outDir, 'styles-css.ts');

console.log('Building Tailwind CSS...');

mkdirSync(outDir, { recursive: true });

execSync(
  `npx tailwindcss -i "${join(workerDir, 'src', 'styles.css')}" -o "${cssPath}" --minify`,
  { cwd: workerDir, stdio: 'inherit' }
);

const css = readFileSync(cssPath, 'utf-8');
const ts = `// Auto-generated by scripts/build-css.ts. Do not edit manually.\nexport const STYLES_CSS = ${JSON.stringify(css)};\n`;
writeFileSync(tsPath, ts, 'utf-8');

console.log(`✅ Tailwind CSS built and inlined (${(css.length / 1024).toFixed(2)} KB)`);
console.log(`Output: ${tsPath}`);
