#!/usr/bin/env node

/**
 * Build script to inline HTML templates for the main worker
 * This reads HTML files from templates/ and creates a TypeScript file with inlined strings
 */

import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const TEMPLATES_DIR = path.join(__dirname, '..', 'packages', 'main-worker', 'templates');
const OUTPUT_FILE = path.join(__dirname, '..', 'packages', 'main-worker', 'src', 'generated', 'html-templates.ts');

async function buildTemplates() {
  console.log('📦 Building HTML templates...\n');
  
  try {
    // Ensure output directory exists
    await fs.mkdir(path.dirname(OUTPUT_FILE), { recursive: true });
    
    // Get all HTML files in templates directory
    const files = await fs.readdir(TEMPLATES_DIR);
    const htmlFiles = files.filter(file => file.endsWith('.html'));
    
    if (htmlFiles.length === 0) {
      console.log('❌ No HTML files found in templates directory');
      process.exit(1);
    }
    
    const templateExports: string[] = [];
    const fileStats: Array<{ name: string; size: string }> = [];
    
    for (const fileName of htmlFiles) {
      const filePath = path.join(TEMPLATES_DIR, fileName);
      const content = await fs.readFile(filePath, 'utf-8');
      
      // Create variable name from filename (e.g., dashboard.html -> DASHBOARD_HTML)
      const varName = fileName
        .replace('.html', '')
        .toUpperCase()
        .replace(/[^A-Z0-9]/g, '_') + '_HTML';
      
      // Escape backticks and ${} for template literals
      const escapedContent = content
        .replace(/\\/g, '\\\\')  // Escape backslashes
        .replace(/\`/g, '\\`')      // Escape backticks
        .replace(/\$/g, '\\$');     // Escape dollar signs
      
      templateExports.push(`export const ${varName} = \`${escapedContent}\`;`);
      
      // Format file size
      const size = (Buffer.byteLength(content, 'utf-8') / 1024).toFixed(2);
      fileStats.push({ name: fileName, size });
      
      console.log(`  • ${fileName} (${size} KB) → ${varName}`);
    }
    
    // Generate the TypeScript file
    const tsContent = `// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
// This file is generated by scripts/build-html.ts
// Last generated: ${new Date().toISOString()}

${templateExports.join('\n\n')}
`;
    
    await fs.writeFile(OUTPUT_FILE, tsContent, 'utf-8');
    
    console.log(`\n✅ Templates built successfully!\n\nOutput: ${OUTPUT_FILE}`);
    
  } catch (error) {
    console.error('❌ Build failed:', error);
    process.exit(1);
  }
}

buildTemplates();